name: be_fit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.2.0-34.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  jiffy: ^5.0.1
  syncfusion_flutter_charts: ^24.1.45+2
  video_player: ^2.7.1
  wheel_slider: ^1.2.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  fluttertoast: ^8.0.2
  custom_refresh_indicator: ^3.0.0
  flutter_native_splash: ^2.3.10
  page_transition: ^2.1.0
  flutter_spinkit: ^5.2.1
  animation_list: ^3.0.0
  panara_dialogs: ^0.1.5
  animated_snack_bar: ^0.4.0
  chewie: ^1.7.5
  draggable_bottom_sheet: ^1.0.2
  flutter_offline: ^3.0.1
  flutter_easyloading: ^3.0.5
  flutter_popup: ^3.3.0
  bottom_navy_bar: ^6.0.0
  easy_stepper: ^0.8.5+1
  stop_watch_timer: ^3.1.1
  showcaseview: ^3.0.0

  #responsive ui
  flutter_screenutil: ^5.9.3

  #state management
  multiple_result: ^5.1.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3

  #cacheing
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

  #other
  connectivity_plus: ^5.0.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.3
  share_plus: ^7.2.1
  permission_handler: ^11.3.1
  rename: ^3.0.2
  equatable: ^2.0.5
  in_app_review: ^2.0.9
  in_app_update: ^4.2.3
  device_preview: ^1.1.0
  audioplayers: ^5.2.1

  #Firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.5.3
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.0


flutter_native_splash:
  color: "#ffffff"
  image: images/be-fit_logo.png
  background_image: images/be-fit_logo.png
  android_12:
    image: images/be-fit_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/beFit_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/audio/
#    - icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
