name: be_fit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-34.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  jiffy: ^5.0.1
  syncfusion_flutter_charts: ^24.1.45+2
  image_picker: ^1.0.4
  video_player: ^2.7.1
  shared_preferences: ^2.2.2
  wheel_slider: ^1.2.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  fluttertoast: ^8.0.2
  url_launcher: ^6.2.3
  custom_refresh_indicator: ^3.0.0
  share_plus: ^7.2.1
  flutter_native_splash: ^2.3.10
  multiple_result: ^5.1.0
  permission_handler: ^11.3.1
  page_transition: ^2.1.0
  rename: ^3.0.2
  equatable: ^2.0.5


  firebase_core: ^2.16.0
  firebase_auth: ^4.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.5.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.8.0


flutter_native_splash:
  color: "#444444"
  image: images/beFit_icon.png
  background_image: images/beFit_icon.png
  android_12:
    image: images/beFit_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/beFit_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
#    - icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
